#!/usr/bin/env python3
"""Generate the PS3 PRX import tables for the iPSX3 Test Cart.

SPDX-License-Identifier: GPL-2.0-or-later

A PS3 executable declares its HLE imports through a program header of type 0x60000002 that points
at a ppu_proc_prx_param_t (magic 0x1b434cec), whose libstub range is an array of 44-byte
ppu_prx_module_info records.  RPCS3 walks exactly that (Emu/Cell/PPUModule.cpp:2506 and :971) and
overwrites each entry of the module's `addrs` array with the address of the HLE trampoline for that
function's NID.  Nothing here is Sony code: it is a data layout the emulator reads.

NIDs are COMPUTED, not copied from a table, with the same function RPCS3 uses
(ppu_generate_id, Emu/Cell/PPUModule.cpp:56): the first four bytes, little-endian, of
SHA-1(name || suffix).  Verified against two values seen in a real boot log:
cellGcmSetInvalidateTile = 0xbd6d60d9, cellOvisInvalidateOverlappedSegments = 0x629ba0c0.
"""
import hashlib, struct, sys, os

SUFFIX = bytes([0x67, 0x59, 0x65, 0x99, 0x04, 0x25, 0x04, 0x90,
                0x56, 0x64, 0x27, 0x49, 0x94, 0x89, 0x74, 0x1A])

def nid(name):
    return struct.unpack("<I", hashlib.sha1(name.encode() + SUFFIX).digest()[:4])[0]

# module name -> the functions we import from it, in the order the generated header indexes them.
# Only the pad.  Graphics goes through the sys_rsx syscalls instead of cellGcmSys, because every
# sys_rsx entry point sets cpu_flag::wait on the calling thread before touching vm
# (Emu/Cell/lv2/sys_rsx.cpp) while _cellGcmInitBody does not -- calling the latter from a plain
# guest thread dies in vm::writer_lock ("is being used without cpu_flag::wait set by the caller",
# vm.cpp:1290), which is exactly what happened when this was first wired through cellGcmSys.
MODULES = {
    "sys_io": [
        "cellPadInit",
        "cellPadEnd",
        "cellPadClearBuf",
        "cellPadSetPortSetting",
        "cellPadGetData",
    ],
}

def c_ident(s):
    return "".join(ch if ch.isalnum() else "_" for ch in s)

def gen_asm():
    o = []
    o.append('/* GENERATED by tools/mkimports.py -- do not edit. */')
    o.append('    .section .prx_param, "a", @progbits')
    o.append('    .p2align 3')
    o.append('    .globl __ps3_prx_param')
    o.append('__ps3_prx_param:')
    o.append('    .long   0x00000040          /* size */')
    o.append('    .long   0x1b434cec          /* magic (PPUModule.cpp:2532) */')
    o.append('    .long   0x00000004          /* version */')
    o.append('    .long   0                   /* unk0 */')
    o.append('    .long   0                   /* libent_start: we export nothing */')
    o.append('    .long   0                   /* libent_end */')
    o.append('    .long   __libstub_start')
    o.append('    .long   __libstub_end')
    o.append('    .short  0                   /* ver */')
    o.append('    .short  0                   /* unk1 */')
    o.append('    .long   0                   /* unk2 */')
    o.append('')
    o.append('    .section .lib.stub, "a", @progbits')
    o.append('    .p2align 2')
    o.append('    .globl __libstub_start')
    o.append('__libstub_start:')
    for mod, fns in MODULES.items():
        m = c_ident(mod)
        o.append(f'    /* ---- {mod}: {len(fns)} function(s) ---- */')
        o.append('    .byte   0x2c                /* size = sizeof(ppu_prx_module_info) */')
        o.append('    .byte   0                   /* unk0 */')
        o.append('    .short  0x0001              /* version */')
        o.append('    .short  0x0009              /* attributes (0x2000 = extra frefs: NOT set) */')
        o.append(f'    .short  {len(fns)}                   /* num_func */')
        o.append('    .short  0                   /* num_var */')
        o.append('    .short  0                   /* num_tlsvar */')
        o.append('    .byte   0                   /* info_hash */')
        o.append('    .byte   0                   /* info_tlshash */')
        o.append('    .byte   0, 0                /* unk1[2] */')
        o.append(f'    .long   __modname_{m}')
        o.append(f'    .long   __nids_{m}')
        o.append(f'    .long   __imp_{m}')
        o.append('    .long   0                   /* vnids */')
        o.append('    .long   0                   /* vstubs */')
        o.append('    .long   0                   /* unk4 */')
        o.append('    .long   0                   /* unk5 */')
    o.append('    .globl __libstub_end')
    o.append('__libstub_end:')
    o.append('')
    o.append('    .section .rodata.imports, "a", @progbits')
    o.append('    .p2align 2')
    for mod, fns in MODULES.items():
        m = c_ident(mod)
        o.append(f'__modname_{m}:')
        o.append(f'    .asciz  "{mod}"')
        o.append('    .p2align 2')
        o.append(f'__nids_{m}:')
        for f in fns:
            o.append(f'    .long   0x{nid(f):08x}          /* {f} */')
    o.append('')
    o.append('/* The loader WRITES the resolved trampoline address into each slot, so this table must')
    o.append('   live in a writable section. */')
    o.append('    .section .data.imports, "aw", @progbits')
    o.append('    .p2align 2')
    for mod, fns in MODULES.items():
        m = c_ident(mod)
        o.append(f'    .globl __imp_{m}')
        o.append(f'__imp_{m}:')
        for f in fns:
            o.append(f'    .long   0                   /* {f} */')
    return "\n".join(o) + "\n"

def gen_header():
    o = ['/* GENERATED by tools/mkimports.py -- do not edit. */',
         '#ifndef IPSX3_TESTCART_IMPORTS_H',
         '#define IPSX3_TESTCART_IMPORTS_H', '']
    for mod, fns in MODULES.items():
        m = c_ident(mod)
        o.append(f'extern volatile unsigned int __imp_{m}[];')
        for i, f in enumerate(fns):
            o.append(f'#define IMP_{f} (__imp_{m}[{i}])')
        o.append('')
    o.append('/* Calling an import.')
    o.append(' *')
    o.append(' * The loader writes a FUNCTION DESCRIPTOR address into the slot, not a code address')
    o.append(' * (PPUModule.cpp:1022 stores flink.export_addr = ppu_function_manager::func_addr(index),')
    o.append(' * and :345-368 builds that table as a "double-purpose fake OPD" whose two words are')
    o.append(' * {code = self + 4, rtoc = 0}).  Branching to the descriptor itself lands on the entry')
    o.append(' * registered as a null function and faults -- which is exactly what happened the first')
    o.append(' * time this was wired up: "Segfault executing location cccccccccccccccc".')
    o.append(' *')
    o.append(' * So dereference the descriptor and call its code word.  rtoc is deliberately 0 for HLE')
    o.append(' * functions, so r2 is left alone rather than reloaded from it.  Reading it through a')
    o.append(' * volatile pointer also keeps the compiler from hoisting the load above the check.')
    o.append(' */')
    o.append('static inline unsigned long imp_code(volatile unsigned int *slot)')
    o.append('{')
    o.append('    unsigned int opd = *slot;')
    o.append('    if (!opd) return 0;')
    o.append('    return (unsigned long)*(volatile unsigned int *)(unsigned long)opd;')
    o.append('}')
    o.append('')
    o.append('#define IMP_RESOLVED(slot) (imp_code(&(slot)) != 0)')
    o.append('#define IMP_CALL(slot, type) ((type)imp_code(&(slot)))')
    o.append('')
    o.append('#endif')
    return "\n".join(o) + "\n"

if __name__ == "__main__":
    outdir = sys.argv[1] if len(sys.argv) > 1 else "gen"
    os.makedirs(outdir, exist_ok=True)
    open(os.path.join(outdir, "prx_imports.S"), "w").write(gen_asm())
    open(os.path.join(outdir, "imports.h"), "w").write(gen_header())
    print("generated", outdir + "/prx_imports.S", "and", outdir + "/imports.h")
